//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.Cumprimentar_Client__.NET.br.gharralabs.services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.gharralabs.br/", ConfigurationName="br.gharralabs.services.HelloServiceImpl")]
    public interface HelloServiceImpl {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gharralabs.br/HelloServiceImpl/cumprimentarRequest", ReplyAction="http://services.gharralabs.br/HelloServiceImpl/cumprimentarResponse")]
        _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarResponse cumprimentar(_02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gharralabs.br/HelloServiceImpl/cumprimentarRequest", ReplyAction="http://services.gharralabs.br/HelloServiceImpl/cumprimentarResponse")]
        System.Threading.Tasks.Task<_02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarResponse> cumprimentarAsync(_02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cumprimentarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cumprimentar", Namespace="http://services.gharralabs.br/", Order=0)]
        public _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequestBody Body;
        
        public cumprimentarRequest() {
        }
        
        public cumprimentarRequest(_02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cumprimentarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public cumprimentarRequestBody() {
        }
        
        public cumprimentarRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cumprimentarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cumprimentarResponse", Namespace="http://services.gharralabs.br/", Order=0)]
        public _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarResponseBody Body;
        
        public cumprimentarResponse() {
        }
        
        public cumprimentarResponse(_02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cumprimentarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public cumprimentarResponseBody() {
        }
        
        public cumprimentarResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloServiceImplChannel : _02.Cumprimentar_Client__.NET.br.gharralabs.services.HelloServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceImplClient : System.ServiceModel.ClientBase<_02.Cumprimentar_Client__.NET.br.gharralabs.services.HelloServiceImpl>, _02.Cumprimentar_Client__.NET.br.gharralabs.services.HelloServiceImpl {
        
        public HelloServiceImplClient() {
        }
        
        public HelloServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarResponse _02.Cumprimentar_Client__.NET.br.gharralabs.services.HelloServiceImpl.cumprimentar(_02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequest request) {
            return base.Channel.cumprimentar(request);
        }
        
        public string cumprimentar(string arg0) {
            _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequest inValue = new _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequest();
            inValue.Body = new _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequestBody();
            inValue.Body.arg0 = arg0;
            _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarResponse retVal = ((_02.Cumprimentar_Client__.NET.br.gharralabs.services.HelloServiceImpl)(this)).cumprimentar(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarResponse> _02.Cumprimentar_Client__.NET.br.gharralabs.services.HelloServiceImpl.cumprimentarAsync(_02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequest request) {
            return base.Channel.cumprimentarAsync(request);
        }
        
        public System.Threading.Tasks.Task<_02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarResponse> cumprimentarAsync(string arg0) {
            _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequest inValue = new _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequest();
            inValue.Body = new _02.Cumprimentar_Client__.NET.br.gharralabs.services.cumprimentarRequestBody();
            inValue.Body.arg0 = arg0;
            return ((_02.Cumprimentar_Client__.NET.br.gharralabs.services.HelloServiceImpl)(this)).cumprimentarAsync(inValue);
        }
    }
}
